### ISSUE TITLE
dislocation line intersect with each other in visualization

### ISSUE THREAD

**Issue by YiYangddd** [adevaucorbeil/ArealGlide#3]
[randomver100.zip](https://github.com/adevaucorbeil/ArealGlide/files/7629736/randomver100.zip)
dislocation line in the simulation of randomly distributed 100 rods will intersect with each other, an example file has been attached. if you could take a look? thanks.

**Comment by adevaucorbeil** [comment]
Yi. There was an issue in the post-processing. It should be fixed now.
